# Generated by Django 5.2.7 on 2025-10-11 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'is_available'], name='books_book_categor_dcc7da_idx'),
        ),
    ]
