# Generated by Django 5.2.7 on 2025-10-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_books_book_categor_dcc7da_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the slide', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='banners/videos/')),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to link to')),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
