# Generated by Django 5.2.7 on 2025-10-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bannerslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerSlide',
        ),
    ]
