# Generated by Django 5.2.7 on 2025-10-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
