# Generated by Django 5.2.7 on 2025-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('requested', 'Requested'), ('handover_confirmed', 'Handover Confirmed'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
