# Generated by Django 5.2.7 on 2025-10-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_quantity'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
