# Generated by Django 5.2.7 on 2025-10-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_quantity'),
        ('requests', '0002_bookrequest_book_bookrequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='matched_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_books', to='books.book'),
        ),
    ]
