# Generated by Django 5.2.7 on 2025-10-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_status'),
        ('requests', '0003_bookrequest_matched_book_alter_bookrequest_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='donations.donation'),
        ),
    ]
