# Generated by Django 5.2.7 on 2025-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_handover_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed by Buyer'), ('seller_confirmed', 'Confirmed by Seller'), ('cancelled', 'Cancelled'), ('handover_pending', 'Ready for Handover'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
